# Generated by Django 4.2.3 on 2023-07-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='account.account'),
        ),
        migrations.AddField(
            model_name='operation',
            name='type_transaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='type_transaction', to='account.typetransaction'),
        ),
    ]
