# Generated by Django 4.2.3 on 2023-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_operation_type_transaction_operation_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='TypeTransaction',
        ),
        migrations.AddField(
            model_name='category',
            name='TypeTransaction',
            field=models.BooleanField(default=True),
        ),
    ]
