# Generated by Django 4.2.3 on 2023-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_type_typetransaction_category_typetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(),
        ),
    ]
